import { CheckCircle2, Eye, Link2, TriangleAlert } from 'lucide-react'
import { useMemo, useState } from 'react'
import { PageHeader } from '../components/ui/PageHeader'
import { StatusBadge } from '../components/ui/StatusBadge'
import { useLocalDatabase } from '../hooks/useLocalDatabase'
import { createId } from '../lib/localDb'

export function ReconciliationPage() {
  const { database, updateDatabase } = useLocalDatabase()
  const [selected, setSelected] = useState<string | null>(null)
  const rows = useMemo(() => database.salesOrders.map((order) => ({ order, uploadedQty: order.channel === 'SHOPEE' ? order.items.reduce((sum, item) => sum + item.qty, 0) : 0, manualQty: order.channel === 'SHOPEE' ? (order.externalOrderId.endsWith('002') ? 1 : order.items.reduce((sum, item) => sum + item.qty, 0)) : order.items.reduce((sum, item) => sum + item.qty, 0) })), [database.salesOrders])
  const conflicts = rows.filter((row) => row.uploadedQty !== row.manualQty).length

  function resolve(orderId: string, action: string) {
    const order = database.salesOrders.find((item) => item.id === orderId)
    if (!order) return
    updateDatabase((current) => ({ ...current, audits: [{ id: createId('audit'), date: '2026-10-07 09:00', action: 'RECONCILIATION_RESOLVED', entity: order.externalOrderId, detail: action }, ...current.audits] }))
    setSelected(null)
  }

  return <div className="space-y-7"><PageHeader title="Daily Reconciliation" description="Bandingkan laporan upload, catatan manual, expected movement, dan posted movement. Selisih tidak dikoreksi otomatis." action={<div className="rounded-xl border border-stone-200 bg-shell px-4 py-3 text-sm text-stone-600">7 Oktober 2026</div>} />
    <div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-stone-200 bg-shell p-5 shadow-panel"><p className="text-sm text-stone-500">Record diperiksa</p><p className="mt-4 font-display text-3xl font-semibold">{rows.length}</p></div><div className="rounded-2xl border border-stone-200 bg-shell p-5 shadow-panel"><p className="text-sm text-stone-500">Matched</p><p className="mt-4 font-display text-3xl font-semibold">{rows.length - conflicts}</p></div><div className="rounded-2xl border border-amber bg-amber/45 p-5 shadow-panel"><p className="text-sm text-amber-950">Perlu ditinjau</p><p className="mt-4 font-display text-3xl font-semibold text-amber-950">{conflicts}</p></div></div>
    <section className="overflow-hidden rounded-2xl border border-stone-200 bg-shell shadow-panel"><div className="border-b border-stone-100 px-6 py-4"><h2 className="font-display text-lg font-semibold">Reconciliation records</h2><p className="mt-1 text-sm text-stone-500">Uploaded records dan manual records ditampilkan berdampingan.</p></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-linen text-xs text-stone-500"><tr><th className="px-6 py-3 font-semibold">Reference</th><th className="px-6 py-3 font-semibold">SKU</th><th className="px-6 py-3 font-semibold">Uploaded qty</th><th className="px-6 py-3 font-semibold">Manual qty</th><th className="px-6 py-3 font-semibold">Posted</th><th className="px-6 py-3 font-semibold">Status</th><th className="px-6 py-3 text-right font-semibold">Action</th></tr></thead><tbody className="divide-y divide-stone-100">{rows.map(({ order, uploadedQty, manualQty }) => { const matched = uploadedQty === manualQty; const posted = order.allocations.some((allocation) => allocation.posted); return <tr key={order.id}><td className="px-6 py-4 font-semibold">{order.externalOrderId}</td><td className="px-6 py-4 text-stone-600">{order.items.map((item) => database.skus.find((sku) => sku.id === item.skuId)?.sellerSku).join(', ')}</td><td className="px-6 py-4">{uploadedQty}</td><td className="px-6 py-4">{manualQty}</td><td className="px-6 py-4">{posted ? 'Ya' : 'Belum'}</td><td className="px-6 py-4">{matched ? <StatusBadge label="MATCHED" tone="positive" /> : <StatusBadge label="CONFLICT" tone="warning" />}</td><td className="px-6 py-4 text-right"><button type="button" onClick={() => setSelected(order.id)} className="inline-flex items-center gap-1 rounded-lg border border-stone-200 px-3 py-2 text-xs font-semibold hover:bg-linen"><Eye className="h-3.5 w-3.5" /> Review</button></td></tr> })}</tbody></table></div></section>
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/25 p-5"><div className="w-full max-w-lg rounded-2xl bg-shell p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="font-display text-xl font-semibold">Review reconciliation</h2><p className="mt-1 text-sm text-stone-500">Pilih tindakan eksplisit untuk menyelesaikan perbedaan.</p></div><button type="button" onClick={() => setSelected(null)} className="text-sm text-stone-500">Tutup</button></div><div className="mt-6 space-y-3"><div className="flex items-start gap-3 rounded-xl bg-amber/45 p-4 text-sm text-amber-950"><TriangleAlert className="mt-0.5 h-4 w-4 shrink-0" /><span>Perbedaan tidak otomatis menjadi adjustment. Periksa sumber fisik terlebih dahulu.</span></div><div className="rounded-xl bg-linen p-4 text-sm text-stone-700"><p className="font-semibold">Uploaded record</p><p className="mt-1">Data dari Order.all atau laporan sumber.</p></div><div className="rounded-xl bg-linen p-4 text-sm text-stone-700"><p className="font-semibold">Manual record</p><p className="mt-1">Catatan operasional manusia untuk dibandingkan.</p></div></div><div className="mt-6 grid gap-2 sm:grid-cols-3"><button type="button" onClick={() => resolve(selected, 'Matched by operator')} className="rounded-lg border border-stone-200 px-3 py-2.5 text-xs font-semibold hover:bg-linen"><Link2 className="mr-1 inline h-3.5 w-3.5" /> Match</button><button type="button" onClick={() => resolve(selected, 'Ignored with reason: valid manual difference')} className="rounded-lg border border-stone-200 px-3 py-2.5 text-xs font-semibold hover:bg-linen">Ignore dengan alasan</button><button type="button" onClick={() => resolve(selected, 'Resolved as explicit adjustment')} className="rounded-lg bg-ink px-3 py-2.5 text-xs font-semibold text-white"><CheckCircle2 className="mr-1 inline h-3.5 w-3.5" /> Resolve</button></div></div></div>}
  </div>
}
