import { useState } from 'react'
import { FileText, Plus, Receipt, Save, ToggleLeft, ToggleRight, UsersRound, X } from 'lucide-react'
import { PageHeader } from '../components/ui/PageHeader'
import { StatusBadge } from '../components/ui/StatusBadge'
import { useLocalDatabase } from '../hooks/useLocalDatabase'
import type { FinancialAccount, InvoiceSettings, Supplier, WorkspaceMember } from '../lib/localDb'
import { createId } from '../lib/localDb'
import { formatIdr } from '../lib/money'

type SettingsView = 'users' | 'suppliers' | 'accounts' | 'invoices' | 'audit'
type Modal = 'supplier' | 'member' | 'account' | null

const accountTypeLabels: Record<FinancialAccount['type'], string> = {
  CASH_BANK: 'Cash / bank', MARKETPLACE: 'Marketplace liquid', PENDING: 'Pending settlement',
  PREPAID_ASSET: 'Prepaid asset', CREDIT_CARD: 'Credit card', LOAN: 'Loan'
}
const permissionLabels: Record<string, string> = { dashboard: 'Dashboard', inventory: 'Inventory', restock: 'Restock', supplier_deposit: 'Deposit', shopee_orders: 'Shopee', manual_orders: 'Manual', b2b: 'B2B', finance: 'Finance', reports: 'Reports', settings: 'Settings' }

export function SettingsPage({ view }: { view: SettingsView }) {
  const { database, updateDatabase } = useLocalDatabase()
  const [modal, setModal] = useState<Modal>(null)
  const addAudit = (current: typeof database, action: string, entity: string, detail: string) => ({ ...current, audits: [{ id: createId('audit'), date: '2026-10-07 09:00', action, entity, detail }, ...current.audits] })
  const saveSupplier = (supplier: Supplier) => { updateDatabase((current) => addAudit({ ...current, suppliers: [...current.suppliers, supplier] }, 'SUPPLIER_CREATED', supplier.code, `${supplier.name} ditambahkan ke supplier master`)); setModal(null) }
  const saveMember = (member: WorkspaceMember) => { updateDatabase((current) => addAudit({ ...current, workspaceMembers: [...current.workspaceMembers, member] }, 'MEMBER_CREATED', member.email, `${member.name} ditambahkan sebagai ${member.role}`)); setModal(null) }
  const saveAccount = (account: FinancialAccount) => { updateDatabase((current) => addAudit({ ...current, financialAccounts: [...current.financialAccounts, account] }, 'ACCOUNT_CREATED', account.name, `Akun ${accountTypeLabels[account.type]} dibuat`)); setModal(null) }
  const toggleMember = (member: WorkspaceMember) => updateDatabase((current) => addAudit({ ...current, workspaceMembers: current.workspaceMembers.map((item) => item.id === member.id ? { ...item, active: !item.active } : item) }, 'MEMBER_STATUS_CHANGED', member.email, `${member.name} ${member.active ? 'dinonaktifkan' : 'diaktifkan'}`))
  const toggleAccount = (account: FinancialAccount) => updateDatabase((current) => addAudit({ ...current, financialAccounts: current.financialAccounts.map((item) => item.id === account.id ? { ...item, active: !item.active } : item) }, 'ACCOUNT_STATUS_CHANGED', account.name, `${account.name} ${account.active ? 'dinonaktifkan' : 'diaktifkan'}`))

  if (view === 'suppliers') return <><div className="space-y-7"><PageHeader title="Suppliers" description="Supplier master untuk HPP, dropship, restock, dan supplier deposit." action={<button type="button" onClick={() => setModal('supplier')} className="inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white"><Plus className="h-4 w-4" /> Tambah supplier</button>} /><section className="grid gap-4 md:grid-cols-2">{database.suppliers.map((supplier) => <div key={supplier.id} className="rounded-2xl border border-stone-200 bg-shell p-6 shadow-panel"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-blush/35 p-2.5"><UsersRound className="h-5 w-5 text-blushDeep" /></div><div><h2 className="font-display text-lg font-semibold">{supplier.name}</h2><p className="mt-1 text-xs text-stone-500">Kode {supplier.code}</p></div></div><StatusBadge label={supplier.active ? 'Aktif' : 'Nonaktif'} tone={supplier.active ? 'positive' : 'neutral'} /></div><div className="mt-6 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-linen p-3"><p className="text-xs text-stone-500">SKU terhubung</p><p className="mt-1 font-semibold">{database.skus.filter((sku) => sku.supplierId === supplier.id).length}</p></div><div className="rounded-xl bg-linen p-3"><p className="text-xs text-stone-500">Deposit ledger</p><p className="mt-1 font-semibold">{database.depositMovements.filter((movement) => movement.supplierId === supplier.id).length} entries</p></div></div></div>)}</section></div>{modal === 'supplier' && <SupplierModal onClose={() => setModal(null)} onSave={saveSupplier} />}</>

  if (view === 'users') return <><div className="space-y-7"><PageHeader title="Users dan Permissions" description="Atur anggota workspace dan akses per modul. Perubahan tersimpan di local workspace untuk preview Phase 1." action={<button type="button" onClick={() => setModal('member')} className="inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white"><Plus className="h-4 w-4" /> Tambah anggota</button>} /><section className="overflow-hidden rounded-2xl border border-stone-200 bg-shell shadow-panel"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-linen text-xs text-stone-500"><tr><th className="px-6 py-3 font-semibold">Anggota</th><th className="px-6 py-3 font-semibold">Role</th><th className="px-6 py-3 font-semibold">Permission</th><th className="px-6 py-3 font-semibold">Status</th><th className="px-6 py-3 font-semibold">Aksi</th></tr></thead><tbody className="divide-y divide-stone-100">{database.workspaceMembers.map((member) => <tr key={member.id}><td className="px-6 py-4"><p className="font-semibold">{member.name}</p><p className="mt-1 text-xs text-stone-500">{member.email}</p></td><td className="px-6 py-4"><StatusBadge label={member.role} tone={member.role === 'OWNER' ? 'positive' : 'neutral'} /></td><td className="max-w-sm px-6 py-4"><div className="flex flex-wrap gap-1.5">{Object.entries(member.permissions).filter(([key, value]) => key !== '*' && value !== 'none').map(([key, value]) => <span key={key} className="rounded-full bg-linen px-2 py-1 text-[11px] text-stone-600">{permissionLabels[key] ?? key}: {value}</span>)}{member.permissions['*'] && <span className="rounded-full bg-blush/40 px-2 py-1 text-[11px] text-blushDeep">Semua modul</span>}</div></td><td className="px-6 py-4"><StatusBadge label={member.active ? 'Aktif' : 'Nonaktif'} tone={member.active ? 'positive' : 'neutral'} /></td><td className="px-6 py-4"><button type="button" onClick={() => toggleMember(member)} className="inline-flex items-center gap-2 rounded-lg border border-stone-200 px-3 py-2 text-xs font-semibold hover:bg-linen">{member.active ? <ToggleRight className="h-4 w-4 text-green-700" /> : <ToggleLeft className="h-4 w-4" />}{member.active ? 'Nonaktifkan' : 'Aktifkan'}</button></td></tr>)}</tbody></table></div></section></div>{modal === 'member' && <MemberModal onClose={() => setModal(null)} onSave={saveMember} />}</>

  if (view === 'accounts') return <><div className="space-y-7"><PageHeader title="Financial Accounts" description="Daftar akun kas, marketplace, pending settlement, prepaid asset, kartu kredit, dan loan." action={<button type="button" onClick={() => setModal('account')} className="inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white"><Plus className="h-4 w-4" /> Tambah akun</button>} /><section className="grid gap-4 md:grid-cols-2">{database.financialAccounts.map((account) => <div key={account.id} className="rounded-2xl border border-stone-200 bg-shell p-6 shadow-panel"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-stone-400">{accountTypeLabels[account.type]}</p><h2 className="mt-2 font-display text-lg font-semibold">{account.name}</h2></div><button type="button" onClick={() => toggleAccount(account)} aria-label={account.active ? 'Nonaktifkan akun' : 'Aktifkan akun'}>{account.active ? <ToggleRight className="h-7 w-7 text-green-700" /> : <ToggleLeft className="h-7 w-7 text-stone-400" />}</button></div><div className="mt-6 flex items-end justify-between"><div><p className="text-xs text-stone-500">Saldo pembukaan</p><p className="mt-1 text-xl font-semibold">{formatIdr(account.openingBalance)}</p></div><StatusBadge label={account.active ? 'Aktif' : 'Nonaktif'} tone={account.active ? 'positive' : 'neutral'} /></div></div>)}</section></div>{modal === 'account' && <AccountModal onClose={() => setModal(null)} onSave={saveAccount} />}</>

  if (view === 'audit') return <div className="space-y-7"><PageHeader title="Audit Log" description="Riwayat tindakan penting di local workspace. Production akan membaca audit_logs dari Supabase." action={<div className="rounded-xl border border-stone-200 bg-shell px-4 py-3 text-sm text-stone-600">{database.audits.length} events</div>} /><section className="overflow-hidden rounded-2xl border border-stone-200 bg-shell shadow-panel"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-linen text-xs text-stone-500"><tr><th className="px-6 py-3 font-semibold">Waktu</th><th className="px-6 py-3 font-semibold">Action</th><th className="px-6 py-3 font-semibold">Entity</th><th className="px-6 py-3 font-semibold">Detail</th></tr></thead><tbody className="divide-y divide-stone-100">{database.audits.map((audit) => <tr key={audit.id}><td className="whitespace-nowrap px-6 py-4 text-stone-500">{audit.date}</td><td className="px-6 py-4"><StatusBadge label={audit.action} tone="neutral" /></td><td className="px-6 py-4 font-medium">{audit.entity}</td><td className="px-6 py-4 text-stone-600">{audit.detail}</td></tr>)}</tbody></table></div></section></div>

  return <InvoiceSettingsView settings={database.invoiceSettings} onSave={(settings) => updateDatabase((current) => addAudit({ ...current, invoiceSettings: settings }, 'INVOICE_SETTINGS_UPDATED', 'invoice_settings', 'Konfigurasi invoice diperbarui'))} />
}

function ModalFrame({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/30 p-4"><div className="w-full max-w-lg rounded-2xl border border-stone-200 bg-shell p-6 shadow-2xl"><div className="flex items-start justify-between"><h2 className="font-display text-xl font-semibold">{title}</h2><button type="button" onClick={onClose} aria-label="Tutup"><X className="h-5 w-5 text-stone-500" /></button></div>{children}</div></div> }
function SupplierModal({ onClose, onSave }: { onClose: () => void; onSave: (supplier: Supplier) => void }) { const [name, setName] = useState(''); const [code, setCode] = useState(''); return <ModalFrame title="Tambah supplier" onClose={onClose}><form className="mt-6 space-y-4" onSubmit={(event) => { event.preventDefault(); if (name.trim() && code.trim()) onSave({ id: createId('supplier'), name: name.trim(), code: code.trim().toUpperCase(), active: true }) }}><Field label="Nama supplier"><input required value={name} onChange={(event) => setName(event.target.value)} className="input" placeholder="Contoh: Nail Supply Jakarta" /></Field><Field label="Kode supplier"><input required value={code} onChange={(event) => setCode(event.target.value)} className="input" placeholder="NSJ" /></Field><ModalActions onClose={onClose} submit="Simpan supplier" /></form></ModalFrame> }
function MemberModal({ onClose, onSave }: { onClose: () => void; onSave: (member: WorkspaceMember) => void }) { const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [role, setRole] = useState<WorkspaceMember['role']>('STAFF'); return <ModalFrame title="Tambah anggota" onClose={onClose}><form className="mt-6 space-y-4" onSubmit={(event) => { event.preventDefault(); if (name.trim() && email.trim()) onSave({ id: createId('member'), name: name.trim(), email: email.trim(), role, active: true, permissions: { dashboard: 'view', inventory: 'view', reports: 'view' } }) }}><Field label="Nama"><input required value={name} onChange={(event) => setName(event.target.value)} className="input" placeholder="Nama anggota" /></Field><Field label="Email"><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="input" placeholder="nama@luminails.local" /></Field><Field label="Role"><select value={role} onChange={(event) => setRole(event.target.value as WorkspaceMember['role'])} className="input"><option value="STAFF">Staff</option><option value="MANAGER">Manager</option><option value="OWNER">Owner</option></select></Field><ModalActions onClose={onClose} submit="Simpan anggota" /></form></ModalFrame> }
function AccountModal({ onClose, onSave }: { onClose: () => void; onSave: (account: FinancialAccount) => void }) { const [name, setName] = useState(''); const [type, setType] = useState<FinancialAccount['type']>('CASH_BANK'); const [openingBalance, setOpeningBalance] = useState('0'); return <ModalFrame title="Tambah akun keuangan" onClose={onClose}><form className="mt-6 space-y-4" onSubmit={(event) => { event.preventDefault(); if (name.trim()) onSave({ id: createId('account'), name: name.trim(), type, openingBalance: Number(openingBalance) || 0, active: true }) }}><Field label="Nama akun"><input required value={name} onChange={(event) => setName(event.target.value)} className="input" placeholder="Contoh: BCA Operasional" /></Field><Field label="Tipe akun"><select value={type} onChange={(event) => setType(event.target.value as FinancialAccount['type'])} className="input">{Object.entries(accountTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Saldo pembukaan"><input type="number" min="0" value={openingBalance} onChange={(event) => setOpeningBalance(event.target.value)} className="input" /></Field><ModalActions onClose={onClose} submit="Simpan akun" /></form></ModalFrame> }

function InvoiceSettingsView({ settings, onSave }: { settings: InvoiceSettings; onSave: (settings: InvoiceSettings) => void }) { const [form, setForm] = useState(settings); const update = (key: keyof InvoiceSettings, value: string | number) => setForm((current) => ({ ...current, [key]: value })); return <div className="space-y-7"><PageHeader title="Invoice Settings" description="Identitas usaha dan penomoran default untuk invoice B2B." action={<button type="button" onClick={() => onSave(form)} className="inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white"><Save className="h-4 w-4" /> Simpan perubahan</button>} /><section className="grid gap-6 lg:grid-cols-[1fr_0.85fr]"><div className="rounded-2xl border border-stone-200 bg-shell p-6 shadow-panel"><div className="mb-5 flex items-center gap-3"><div className="rounded-xl bg-blush/35 p-2.5"><Receipt className="h-5 w-5 text-blushDeep" /></div><div><h2 className="font-display text-lg font-semibold">Identitas invoice</h2><p className="text-sm text-stone-500">Tersimpan di local workspace.</p></div></div><div className="space-y-4"><Field label="Nama usaha"><input value={form.companyName} onChange={(event) => update('companyName', event.target.value)} className="input" /></Field><Field label="Alamat"><textarea value={form.address} onChange={(event) => update('address', event.target.value)} className="input min-h-24" /></Field><Field label="Telepon"><input value={form.phone} onChange={(event) => update('phone', event.target.value)} className="input" /></Field><Field label="Catatan pembayaran"><textarea value={form.paymentNotes} onChange={(event) => update('paymentNotes', event.target.value)} className="input min-h-24" /></Field></div></div><div className="rounded-2xl border border-stone-200 bg-shell p-6 shadow-panel"><div className="mb-5 flex items-center gap-3"><div className="rounded-xl bg-blush/35 p-2.5"><FileText className="h-5 w-5 text-blushDeep" /></div><div><h2 className="font-display text-lg font-semibold">Penomoran</h2><p className="text-sm text-stone-500">Dipakai saat invoice baru dibuat.</p></div></div><div className="space-y-4"><Field label="Prefix invoice"><input value={form.invoicePrefix} onChange={(event) => update('invoicePrefix', event.target.value)} className="input" /></Field><Field label="Nomor berikutnya"><input type="number" min="1" value={form.nextNumber} onChange={(event) => update('nextNumber', Number(event.target.value) || 1)} className="input" /></Field><div className="rounded-xl bg-linen p-4 text-sm text-stone-600">Preview: <span className="font-semibold text-ink">{form.invoicePrefix}-{String(form.nextNumber).padStart(4, '0')}</span></div></div></div></section></div> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-medium text-stone-700"><span className="mb-1.5 block text-xs font-semibold uppercase tracking-[0.08em] text-stone-500">{label}</span>{children}</label> }
function ModalActions({ onClose, submit }: { onClose: () => void; submit: string }) { return <div className="flex justify-end gap-3 pt-3"><button type="button" onClick={onClose} className="rounded-xl border border-stone-200 px-4 py-2.5 text-sm font-semibold text-stone-600">Batal</button><button type="submit" className="rounded-xl bg-ink px-4 py-2.5 text-sm font-semibold text-white">{submit}</button></div> }
