from playwright.sync_api import sync_playwright


def main() -> None:
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(headless=True)
        page = browser.new_page(viewport={"width": 1440, "height": 1000})
        page.goto("http://127.0.0.1:5180/", wait_until="networkidle")
        page.get_by_role("heading", name="Selamat datang kembali.").wait_for()
        page.get_by_text("Mode lokal").wait_for()
        page.wait_for_timeout(1000)
        page.screenshot(path="ui-check.png", full_page=True)
        page.get_by_role("link", name="Inventory dan SKU").click()
        page.get_by_role("heading", name="Inventory dan SKU").wait_for()
        page.get_by_role("link", name="Supplier Deposit").click()
        page.get_by_role("heading", name="Supplier Deposit").wait_for()
        page.get_by_role("link", name="Restock").click()
        page.get_by_role("heading", name="Restock", exact=True).wait_for()
        page.get_by_role("link", name="Shopee Orders").click()
        page.get_by_role("heading", name="Shopee Orders").wait_for()
        page.get_by_role("button", name="Atur sumber").click()
        page.get_by_role("button", name="Post fulfillment").last.click()
        page.get_by_role("link", name="Shopee Orders").click()
        page.get_by_role("heading", name="Shopee Orders", exact=True).wait_for()
        page.get_by_text("POSTED").first.wait_for()
        page.get_by_role("link", name="Restock").click()
        page.get_by_role("heading", name="Restock", exact=True).wait_for()
        page.get_by_role("button", name="Terima barang").click()
        page.locator('input[type="number"]').last.fill("5")
        page.get_by_role("button", name="Simpan penerimaan").click()
        page.get_by_text("PARTIAL").wait_for()
        page.reload(wait_until="networkidle")
        page.get_by_text("PARTIAL").wait_for()
        page.get_by_role("link", name="B2B Orders").click()
        page.get_by_role("heading", name="B2B Orders", exact=True).wait_for()
        page.goto("http://127.0.0.1:5180/orders/manual", wait_until="networkidle")
        page.get_by_role("heading", name="Manual dan Reseller", exact=True).wait_for()
        page.goto("http://127.0.0.1:5180/operations/reconciliation", wait_until="networkidle")
        page.get_by_role("heading", name="Daily Reconciliation", exact=True).wait_for()
        page.get_by_role("link", name="Profit dan Loss").click()
        page.get_by_role("heading", name="Profit dan Loss").wait_for()
        page.goto("http://127.0.0.1:5180/finance/business-position", wait_until="networkidle")
        page.get_by_role("heading", name="Business Position", exact=True).wait_for()
        page.goto("http://127.0.0.1:5180/finance/expenses", wait_until="networkidle")
        page.get_by_role("heading", name="Expenses dan Liabilities", exact=True).wait_for()
        page.get_by_role("link", name="Reports").click()
        page.get_by_role("heading", name="Reports", exact=True).wait_for()
        with page.expect_download() as download_info:
            page.get_by_role("button", name="Download CSV").first.click()
        assert download_info.value.suggested_filename == "luminails-inventory-balance.csv"
        page.goto("http://127.0.0.1:5180/settings/suppliers", wait_until="networkidle")
        page.get_by_role("heading", name="Suppliers", exact=True).wait_for()
        page.get_by_role("button", name="Tambah supplier").click()
        page.get_by_role("textbox", name="Nama supplier").fill("Smoke Supplier")
        page.get_by_role("textbox", name="Kode supplier").fill("SMOKE")
        page.get_by_role("button", name="Simpan supplier").click()
        page.get_by_text("Smoke Supplier").wait_for()
        page.goto("http://127.0.0.1:5180/settings/accounts", wait_until="networkidle")
        page.get_by_role("heading", name="Financial Accounts", exact=True).wait_for()
        page.goto("http://127.0.0.1:5180/settings/invoices", wait_until="networkidle")
        page.get_by_role("heading", name="Invoice Settings", exact=True).wait_for()
        page.goto("http://127.0.0.1:5180/settings/users", wait_until="networkidle")
        page.get_by_role("heading", name="Users dan Permissions", exact=True).wait_for()
        page.goto("http://127.0.0.1:5180/settings/audit-log", wait_until="networkidle")
        page.get_by_role("heading", name="Audit Log", exact=True).wait_for()
        print("dashboard_loaded=true")
        print("local_mode_loaded=true")
        print("inventory_route_loaded=true")
        print("ledger_routes_loaded=true")
        print("settings_and_reports_loaded=true")
        print(f"title={page.title()}")
        browser.close()


if __name__ == "__main__":
    main()
