create table public.sales_orders(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, order_number text not null, external_order_number text, order_date date not null default current_date, channel text not null check(channel in ('SHOPEE','WHATSAPP','B2B','RESELLER','MANUAL','OTHER')), customer_id uuid, address_id uuid, status text not null default 'DRAFT' check(status in ('DRAFT','POSTED','REVERSED','CANCELLED')), normal_subtotal numeric(24,2) not null default 0, selling_subtotal numeric(24,2) not null default 0, adjustment_total numeric(24,2) not null default 0, grand_total numeric(24,2) not null default 0 check(grand_total>=0), marketplace_fee numeric(24,2) check(marketplace_fee>=0), notes text, created_by uuid default auth.uid(), posted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workspace_id,id), unique(workspace_id,order_number), unique(workspace_id,channel,external_order_number), foreign key(workspace_id,customer_id) references public.customers(workspace_id,id), foreign key(workspace_id,address_id) references public.customer_addresses(workspace_id,id));
create table public.sales_order_items(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, sales_order_id uuid not null, sku_id uuid not null, external_item_id text, qty integer not null check(qty>0), normal_unit_price numeric(24,2) not null check(normal_unit_price>=0), selling_unit_price numeric(24,2) not null check(selling_unit_price>=0), description text, unit_cost_snapshot numeric(24,6), normal_line_total numeric(24,2) generated always as(qty*normal_unit_price) stored, selling_line_total numeric(24,2) generated always as(qty*selling_unit_price) stored, unique(workspace_id,id), unique(sales_order_id,external_item_id), foreign key(workspace_id,sales_order_id) references public.sales_orders(workspace_id,id), foreign key(workspace_id,sku_id) references public.skus(workspace_id,id));
alter table public.sales_orders add constraint export_safe_totals check(normal_subtotal<=999999999999999 and selling_subtotal<=999999999999999);
alter table public.sales_order_items add constraint integer_idr_prices check(normal_unit_price=trunc(normal_unit_price) and selling_unit_price=trunc(selling_unit_price));
create table public.sales_order_adjustments(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, sales_order_id uuid not null, adjustment_type text not null check(adjustment_type in ('DISCOUNT','SHIPPING','OTHER')), description text, amount numeric(24,2) not null check(amount<>0), check(adjustment_type<>'DISCOUNT' or amount<0), foreign key(workspace_id,sales_order_id) references public.sales_orders(workspace_id,id));
create table public.fulfillment_allocations(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, sales_order_item_id uuid not null, fulfillment_type text not null check(fulfillment_type in ('LOCAL_STOCK','SUPPLIER')), supplier_id uuid, inventory_location_id uuid, qty integer not null check(qty>0), unit_cost_snapshot numeric(24,6) check(unit_cost_snapshot>=0), procurement_item_id uuid, active boolean not null default true, unique(workspace_id,id), check((fulfillment_type='LOCAL_STOCK' and inventory_location_id is not null and supplier_id is null and procurement_item_id is null) or (fulfillment_type='SUPPLIER' and supplier_id is not null and inventory_location_id is null)), foreign key(workspace_id,sales_order_item_id) references public.sales_order_items(workspace_id,id), foreign key(workspace_id,supplier_id) references public.suppliers(workspace_id,id), foreign key(workspace_id,inventory_location_id) references public.inventory_locations(workspace_id,id), foreign key(workspace_id,procurement_item_id) references public.procurement_items(workspace_id,id));
create table public.invoices(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, sales_order_id uuid, customer_id uuid not null, invoice_number text not null, invoice_date date not null default current_date, due_date date not null, status text not null default 'ISSUED' check(status in ('DRAFT','ISSUED','VOID')), customer_snapshot jsonb not null, address_snapshot jsonb, settings_snapshot jsonb not null default '{}', normal_subtotal numeric(24,2) not null default 0, selling_subtotal numeric(24,2) not null default 0, adjustment_total numeric(24,2) not null default 0, total numeric(24,2) not null check(total>=0), notes text, created_at timestamptz not null default now(), unique(workspace_id,id), unique(workspace_id,invoice_number), foreign key(workspace_id,sales_order_id) references public.sales_orders(workspace_id,id), foreign key(workspace_id,customer_id) references public.customers(workspace_id,id));
create unique index one_active_invoice on public.invoices(sales_order_id) where status<>'VOID';
create table public.invoice_items(id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.workspaces, invoice_id uuid not null, sku_snapshot jsonb not null, description text, qty integer not null check(qty>0), normal_unit_price numeric(24,2) not null, unit_price numeric(24,2) not null, line_total numeric(24,2) not null, foreign key(workspace_id,invoice_id) references public.invoices(workspace_id,id));

create unique index one_active_procurement_allocation on public.fulfillment_allocations(procurement_item_id) where active;
